version: "3.8"

services:
  langfuse-web:
    image: docker.io/langfuse/langfuse:3
    restart: always
    env_file:
      - .env.prod.example
    ports:
      - 3000:3000
    depends_on:
      - clickhouse
      - minio

  langfuse-worker:
    image: docker.io/langfuse/langfuse-worker:3
    restart: always
    env_file:
      - .env.prod.example
    depends_on:
      - clickhouse
      - minio

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server
    restart: always
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse

  minio:
    image: docker.io/minio/minio
    restart: always
    ports:
      - 9090:9000
      - 9091:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: miniosecret
    command: server /data --console-address ":9001"
